config/routes.rb
Worship::Application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root :to => "application#main_fallback"

  resources :posts, path: 'publications'

  resources :activities, only: [:index, :show], path: "fil"#, only: [:destroy], controller: "socializables"

  resources :pages, path: "pages" do
    resources :chants, :controller => "songs", :as => "songs"
  end

  resources :comments

  get 'utilisateurs/se-connecter' => "application#main_fallback"

  get 'notifications/:id' => "notifications#show", as: 'notification'

  # get 'fil' => "socializables#index", :as => "feeds"
  #
  # get 'fil/:id' => "socializables#show", as: "show_activity"

  get 'action' => "socializables#action", :as => "my_action"

  get 'aime(/:likable_type/:likable_id)' => "socializables#like", :as => "like"

  resources :teams

  post "recherche/chants" => "songs#index", :as => "songs_search"

  resources :chants, :controller => "songs", :as => "songs"

  resources :user_song_preferences

  devise_for :users, :path => "utilisateurs", :path_names => {:sign_in => 'se-connecter', :sign_out => 'se-deconnecter', password: 'mot-de-passe', confirmation: 'confirmation', unlock: 'deverrouillage', registration: 'inscription', sign_up: 'nouvelle' }, :controllers => {:registrations => "registrations"}
  devise_scope :user do
    get 'utilisateurs/inscription/mot-de-passe' => "registrations#password", :as => "edit_current_password"
    put 'utilisateurs/inscription/mot-de-passe' => "registrations#update_password", :as => "update_current_password"

    get 'utilisateurs/inscription/parametres-generaux' => "registrations#instruments", :as => "instruments"
    put 'utilisateurs/inscription/parametres-generaux' => "registrations#update_instruments", :as => "update_instruments"

  end

  get "utilisateurs/en-cours" => "users#show", :as => "current_user"
  resources :users, :path => "utilisateurs" do
    # member do
    #   get 'finaliser-mon-compte' => "users#unfinalized", as: "unfinalized"
    # end
  end
  get "utilisateurs/:id/instruments(/:target)" => "users#instruments"
  post "reunions/new" => "meetings#new"
  resources :meetings, :path => "reunions"

  namespace :api do

    get "main" => "api#main"

    get "/recherche/:term(/sur/:classes)" => "searches#index"

    resources :notifications, only: [:index, :destroy, :update] do
      collection do
        get "/page/:page" => "notifications#index"
      end
    end

    get "utilisateurs/courant" => "users#current", as: :current_user

    resources :medias, only: [:create, :destroy, :update]

    resources :users, only: [:create, :update, :show], path: 'utilisateurs' do
      member do
        put 'aime/:activity_id' => "users#toggle_like", :as => "toggle_like"
        post "push" => "users#push_subscribe"
        # FIXME : change post for delete method once we found a way to send endpoint (which is an URL) via the URL param
        post "push/unsubscribe" => "users#push_unsubscribe"
      end
    end

    devise_scope :user do
      post "sessions/se-connecter" => "sessions#create", as: "sessions"
    end

    resources :pages, only: [:index, :create, :show, :update], path: 'pages' do
      collection do
        get "/recherche/:search" => "pages#index"
      end
    end

    resources :instrument_preferences, path: "instruments"
    resources :activities, path: "activites" do
      collection do
        get "/sur/:recipient_type/:recipient_id(/page/:page)" => "activities#index"
        get "/page/:page" => "activities#index"
      end
      resources :comments, path: "commentaires", controller: 'activities/comments'
    end
    resources :posts, path: 'publications', only: [:show, :create, :update, :destroy]
  end

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'
end

app/models/meeting.rb
class Meeting < ApplicationRecord
  include ActsAsFeedable
  include ActsAsNotifiable
  has_many :meeting_users
  has_one :practice
  has_many :meeting_songs

  accepts_nested_attributes_for :meeting_users, :practice, :meeting_songs, reject_if: :all_blank, allow_destroy: true

  validates :start_at, :presence => true
  validates :label, :presence => true

  after_save :format_label, :plan_practice_notifications

  acts_as_commentable

  notifiable({
    content: :label,
    trigger: :after_save,
    notifier: :creator,
    notifieds: lambda{|m|
      m.notifiable_users
    },
    icon: 'calendar-check-o'
  })

  feedable({
    title: lambda{|m|
      title = ""

      if m.creator
        title = "#{m.creator.full_name} a publié "
      end

      title
    },
    image: lambda{|m|
      m.creator ? m.creator.avatar.url(:tiny) : "/images/user.svg"
    }
  })

  def end_at
    Time.at(start_at.to_i + duration) if start_at and start_at.to_i > 0
  end

  def duration_in_hours
  	duration / 3600
  end

  # Notify meeting users (include leader) of the coming prcatice
  def notify_practice
    meeting_users.each do |meeting_user|
      if meeting_user.user and meeting_user.user.email and !meeting_user.was_notified?
        MeetingMailer.notify_practice(meeting_user).deliver
      end
    end
  end

  # => only_self : gets notifiable users only for the current object
  def notifiable_users(only_self: false, origin_notifiable_resolver: nil)
    n_users_ids = []

    # Owner of the meeting
    if self.creator
      n_users_ids << self.creator.id

      # all users from the same page
      # if post was just created
      if self.id_changed? and self.creator.page
        n_users_ids += self.creator.page.users.collect(&:id)
      end
    end

    # Invited users
    if self.meeting_users.present?
      n_users_ids += self.meeting_users.collect(&:id)
    end

    if a = self.activity
      unless only_self
        # And user who commented the post
        if comments = a.comments and comments.count > 0
          comments_notifiable_users_ids = comments.map do |c|
            if c != origin_notifiable_resolver
              c.notifiable_users(only_self: true, origin_notifiable_resolver: self).collect(&:user_id)
            else
              nil
            end
          end
          n_users_ids << comments_notifiable_users_ids.flatten.compact.uniq
        end
      end
    end

    User.where('users.id IN (?)', n_users_ids.flatten.compact.uniq)
  end

  def format_label
    if self.label.present?
      self.label = self.label.capitalize
    end
  end

  def leader
    if meeting_users and lds = meeting_users.leaders
      lds = lds.first
    end
    lds
  end

  def plan_practice_notifications
    if practice
      if practice.reminder > 0
        time_to_send = practice.start_at.to_i - practice.reminder
        diff_in_seconds = time_to_send - Time.now.to_i
        MeetingsWorker.perform_in(diff_in_seconds.seconds,self.id)
      else
        MeetingsWorker.perform_async(self.id)
      end
    end
  end

  def notifiable_content
    self.content.truncate(30)
  end

  def notification_editor
    creator
  end

  def root_activity
    activity
  end

end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :set_meeting, only: [:show, :edit, :update, :destroy]
  before_action :prepare_form, only: [:new, :edit]

  # GET /meetings
  # GET /meetings.json
  def index

    if params[:meeting_id]
      @meeting = Meeting.find(params[:meeting_id])
    end

    respond_to do |f|
      f.json {
        @meetings = Meeting
        start_p = Time.parse(params[:start])
        end_p = Time.parse(params[:end])
        @meetings = @meetings.where("start_at > ?", params[:start])
        if start_p and end_p
          duration = end_p - start_p
          @meetings = @meetings.where("duration < ?", duration)
        end

        render :json => @meetings.map{|m|
          {
              :id => m.id,
              :title => m.label,
              :start => m.start_at,
              :end => m.end_at,
              :url => "/reunions/#{m.id}.js",
              color: '#D42700',
              textColor: 'white'
          }
        }
      }
      f.html
    end
  end

  # GET /meetings/1
  # GET /meetings/1.json
  def show
    respond_to do |f|
      f.html {redirect_to meetings_path(meeting_id: params[:id])}
      f.js {}
    end
    #@meeting = Meeting.find(params[:id])
  end

  # GET /meetings/new
  def new
    @meeting = Meeting.new
    if params[:date]
      @meeting.start_at = Time.parse(params[:date])
    end
    # @meeting.meeting_users.build if @meeting and @meeting.meeting_users.empty?
    # @meeting.meeting_songs.build if @meeting and @meeting.meeting_songs.empty?
    @meeting.practice = Practice.new if @meeting and !@meeting.practice
  end

  # GET /meetings/1/edit
  def edit
    # @meeting.meeting_users.build if @meeting and @meeting.meeting_users.empty?
    # @meeting.meeting_songs.build if @meeting and @meeting.meeting_songs.empty?

    if @meeting and !@meeting.practice
      @meeting.practice = Practice.new
    end
  end
  
  # POST /meetings
  # POST /meetings.json
  def create

    @meeting = Meeting.new(meeting_params)
    respond_to do |format|
      if @meeting.save
        format.html { redirect_to meetings_path, notice: 'La réunion a bien été ajoutée.' }
        format.json { render :show, status: :created, location: @meeting }
      else
        format.html { render :new }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meetings/1
  # PATCH/PUT /meetings/1.json
  def update
    respond_to do |format|
      if @meeting.update(meeting_params)
        format.html { redirect_to meetings_path, notice: 'La réunion a bien été modifiée.' }
        format.json { render :show, status: :ok, location: @meeting }
      else
        format.html { render :edit }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meetings/1
  # DELETE /meetings/1.json
  def destroy
    @meeting.destroy
    respond_to do |format|
      format.html { redirect_to meetings_url, notice: 'La réunion a bien été détruite.' }
      format.json { head :no_content }
    end
  end

  private

    def prepare_form
      if current_user.page
          @users = current_user.page.users
      else
          @users = User.all
      end

      @leader_users = User.leaders

      @instruments = @users.first.instruments
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_meeting
      @meeting = Meeting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def meeting_params
      params.require(:meeting).permit([:start_at, :duration, :label, songs: [], :practice_attributes => [:id, :start_at, :duration, :reminder, :_destroy], :meeting_users_attributes => [:id, :user_id, :is_leader, :instrument, :_destroy], :meeting_songs_attributes => [:id, :leader_id, :song_id, :_destroy]])
    end
end

app/helpers/meetings_helper.rb
module MeetingsHelper

	def duration_in_words(meeting)
		"#{meeting.duration_in_hours} heure#{meeting.duration_in_hours > 1 ? "s" : ""}"
	end

end

app/views/meetings/_detail.html.haml
- meeting ||= nil

- if meeting
  / Nav tabs
  %ul.nav.nav-tabs{:role => "tablist"}
    %li.active
      %a{"data-toggle" => "tab", :href => "#global-info", :role => "tab"} Information Générale
    - if meeting.meeting_songs.present?
      %li
        %a{"data-toggle" => "tab", :href => "#songs", :role => "tab"} Chants

  / Tab panes
  .tab-content
    #global-info.tab-pane.active
      %table.table.table-striped
        %tr
          %th{"colspan" => "2"}
            Réunion
        %tr
          %td
            Date
          %td
            = l meeting.start_at
        %tr
          %td
            Durée
          %td
            = duration_in_words(meeting)
        - if meeting.practice.present? and practice = meeting.practice and practice.start_at
          %tr
            %th{"colspan" => "2"}
              Répétition
            %tr
              %td
                Date
              %td
                = l practice.start_at
            %tr
              %td
                Durée
              %td
                = duration_in_words(practice)
        - if meeting.meeting_users.present?
          %tr
            %th{"colspan" => "2"}
              Participants
          - meeting.meeting_users.each do |m_user|
            %tr
              %td
                = m_user.user.name if m_user.user
                - if m_user.is_leader?
                  (Leader)
                %td
                  = I18n.t("instruments.#{m_user.instrument}")

    #songs.tab-pane
      %table.table.table-striped
        %tr
          %th
            Chant
          %th
            Leader
          %th
            Clé
        - meeting.meeting_songs.each do |m|
          %tr
            %td
              = link_to(m.song.title, song_path(m.song), :target => "_blank") if m.song
            %td
              = m.leader.name if m.leader
            %td
              = m.song.prefered_key(m.leader) if m.song

app/views/meetings/_detail_footer.html.haml
- meeting ||= nil

- if meeting and current_user.is_admin?
	= link_to edit_meeting_path(meeting), remote: true, class: "btn btn-primary pull-right" do
		%span.glyphicon-pencil.glyphicon
		Modifier
	= link_to meeting_path(meeting), method: :delete, class: "btn btn-primary pull-right" do
		%span.glyphicon-trash.glyphicon
		Supprimer

app/views/meetings/_form.html.haml
= simple_form_for(@meeting) do |f|
  = f.error_notification

  %ul.nav.nav-tabs
    %li.active
      = link_to "#meeting", {"data-toggle" => "tab"} do
        Réunion
    %li
      = link_to "#rehearsal", {"data-toggle" => "tab"} do
        Répétition
    %li
      = link_to "#meeting_users", {"data-toggle" => "tab"} do
        Participants
    %li
      = link_to "#songs", {"data-toggle" => "tab"} do
        Chants

  .tab-content#song-panes
    #meeting.tab-pane.active
      .row.tab-pane
        .col-lg-4.col-md-4.col-sm-4.col-xs-4
          = f.input :label
        .col-lg-4.col-md-4.col-sm-4.col-xs-4
          = f.input :start_at, :as => :string, :input_html => { "data-behaviour" => "datepicker", :value => l(@meeting.start_at ? @meeting.start_at : Time.now + 2.day)}
        .col-lg-4.col-md-4.col-sm-4.col-xs-4
          = f.input :duration, :as => :select, :collection => (1..6).map{|numb| ["#{numb} heure#{numb > 1 ? "s" : ""}", numb.hours]}, :include_blank => false

    #rehearsal.tab-pane
      .row
        .col-lg-12

      .row
        = f.simple_fields_for :practice do |practice|
          .col-lg-4.col-md-4.col-sm-4.col-xs-4
            = practice.input :start_at, :as => :string, :input_html => { "data-behaviour" => "datepicker" }
          .col-lg-4.col-md-4.col-sm-4.col-xs-4
            = practice.input :duration, :as => :select, :collection => (1..6).map{|numb| ["#{numb} heure#{numb > 1 ? "s" : ""}", numb.hours]}, :include_blank => false
          .col-lg-4.col-md-4.col-sm-4.col-xs-4
            = practice.input :reminder, :as => :select, :collection => ((0..10).map{|numb| [ (numb == 0 ? "Maintenant" : ("#{numb} jour#{numb > 1 ? "s" : ""} avant")), (numb > 0 ? numb.days : 0)]}), :include_blank => false

    #meeting_users.tab-pane
      .row.nested_form
        .col-lg-12
          = render "shared/cocoon_wrapper", nested_resource_name: "meeting_user", f: f, form_instance: @meeting, disable_auto_load_first_element: true
    #songs.tab-pane
      .row.nested_form
        .col-lg-12
          = render "shared/cocoon_wrapper", nested_resource_name: "meeting_song", f:f, form_instance: @meeting, disable_auto_load_first_element: true
  .row
    .col-lg-12
      = f.button :submit, class: "pull-right real-submit hidden"


:coffee
  auto_load ->
    load_chosens()

app/views/meetings/_meeting_song_fields.html.haml
- f ||= nil
- extra_class ||= ""
- extra_html ||= ""

- if f
  - inputs = []
  - inputs << f.input(:leader_id, :as => :select, :collection => @leader_users.map{|u| [u.name, u.id]}, :include_blank => false, :input_html => { :class => ""}  )
  - inputs << f.input(:song_id, :as => :select, :include_blank => false, :collection => Song.all.map{|s| [s.title, s.id]}, :input_html => {:class => "chosen"})
  = render("shared/cocoon_fields_wrapper", f: f, :nested_fields => inputs, :extra_class => extra_class, extra_html: extra_html)

  :coffee
      view_ready = ->
        load_chosens()
      auto_load(view_ready)

app/views/meetings/_meeting_user_fields.html.haml
- f ||= nil
- index ||= nil # Defines an incremental index of iterations

- if f
  - meeting_user_select_id = "meeting_user_select"
  - meeting_user_instrument_select_id = "meeting_user_instrument_select"
  - inputs = []
  - inputs << f.input(:user_id, :as => :select, :collection => @users.map{|u| [u.name, u.id]}, :include_blank => false, :input_html => { :class => meeting_user_select_id}, :label => false  )
  - inputs << (f.input :instrument, :as => :select, :include_blank => false, :label => false, :collection => ((u = f.object.user and u.instruments) || @instruments).map{|instrument| [I18n.t("instruments.#{instrument}"), instrument]}, :input_html => {:class => meeting_user_instrument_select_id})

  - extra_class = ""
  - extra_html = ""
  - if index == 0
    - inputs << f.input(:is_leader, :as => :hidden, :input_html => {:value => true})
    - extra_class = "is_leader"
    - extra_html = "<h5>Leader</h5>"

  = render("shared/cocoon_fields_wrapper", f: f, :nested_fields => inputs, :extra_class => extra_class, extra_html: extra_html)

  :coffee
    view_ready = ->
      $('.#{meeting_user_select_id}').change ->
        selected_user_id = $(this).val()
        this_select = this
        $.getJSON "/utilisateurs/" + selected_user_id + "/instruments.json", ((instruments) ->
          user_instrument_select = $(this_select).closest('.nested_model_fields').first().find('.#{meeting_user_instrument_select_id}')
          if user_instrument_select.length > 0
            $(user_instrument_select).html('')
            $.each(instruments, ->
              if(this.length > 0)
                label = this[0]
                key = this[1]
                $(user_instrument_select).append("<option value='"+key+"'>" + label + "</option>")
            )
        )
      #$('.#{meeting_user_select_id}').trigger('change')
    auto_load(view_ready)

app/views/meetings/edit.html.haml
= content_for :headers do
  %h1

= content_for :left_column do

  = render 'form'

  = link_to 'Show', @meeting
  \|
  = link_to 'Back', meetings_path

app/views/meetings/edit.js.haml
- content = render "form", :remote => true

= render("shared/modal_append",
    :modal_id => "show_meeting",
    :title => "#{@meeting.label}",
    :content => content,
    :footer => link_to("Enregistrer", "#", "data-form-submit" => "true", :class => "btn btn-primary"))

setTimeout(function(){
auto_load(global_ready);
},100)

app/views/meetings/index.html.haml
.col-md-12

  - if current_user.is_up_to_worship_leader?
    = link_to new_meeting_path, :remote => true, class: "btn btn-primary btn-sm pull-right left-margin" do
      = fa_icon "plus"
      = "Nouvelle réunion"

  #meetings


- if @meeting
  :coffee
    $ ->
      $.ajax
        url: "#{meeting_path(@meeting, format: "js")}"

app/views/meetings/new.html.haml
%h1 New meeting

= render 'form'

= link_to 'Back', meetings_path

app/views/meetings/new.js.haml
- content = render "form", :remote => true

= render("shared/modal_append",
    :modal_id => "new_meeting",
    :title => "Nouvelle réunion",
    :content => content,
    :footer => link_to("Enregistrer", "#", "data-form-submit" => "true", :class => "btn btn-primary"))


setTimeout(function(){
auto_load(global_ready);
},100)

app/views/meetings/show.html.haml
= render "detail", :meeting => @meeting

app/views/meetings/show.js.haml
- content = render "detail", meeting: @meeting
- footer = render "detail_footer", meeting: @meeting

= render("shared/modal_append",
    :modal_id => "show_meeting",
    :title => "#{@meeting.label}",
    :content => content,
    :footer => footer)

setTimeout(function(){
auto_load(global_ready);
},100)