config/routes.rb
Worship::Application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root :to => "application#main_fallback"

  resources :posts, path: 'publications'

  resources :activities, only: [:index, :show], path: "fil"#, only: [:destroy], controller: "socializables"

  resources :pages, path: "pages" do
    resources :chants, :controller => "songs", :as => "songs"
  end

  resources :comments

  get 'utilisateurs/se-connecter' => "application#main_fallback"

  get 'notifications/:id' => "notifications#show", as: 'notification'

  # get 'fil' => "socializables#index", :as => "feeds"
  #
  # get 'fil/:id' => "socializables#show", as: "show_activity"

  get 'action' => "socializables#action", :as => "my_action"

  get 'aime(/:likable_type/:likable_id)' => "socializables#like", :as => "like"

  resources :teams

  post "recherche/chants" => "songs#index", :as => "songs_search"

  resources :chants, :controller => "songs", :as => "songs"

  resources :user_song_preferences

  devise_for :users, :path => "utilisateurs", :path_names => {:sign_in => 'se-connecter', :sign_out => 'se-deconnecter', password: 'mot-de-passe', confirmation: 'confirmation', unlock: 'deverrouillage', registration: 'inscription', sign_up: 'nouvelle' }, :controllers => {:registrations => "registrations"}
  devise_scope :user do
    get 'utilisateurs/inscription/mot-de-passe' => "registrations#password", :as => "edit_current_password"
    put 'utilisateurs/inscription/mot-de-passe' => "registrations#update_password", :as => "update_current_password"

    get 'utilisateurs/inscription/parametres-generaux' => "registrations#instruments", :as => "instruments"
    put 'utilisateurs/inscription/parametres-generaux' => "registrations#update_instruments", :as => "update_instruments"

  end

  get "utilisateurs/en-cours" => "users#show", :as => "current_user"
  resources :users, :path => "utilisateurs" do
    # member do
    #   get 'finaliser-mon-compte' => "users#unfinalized", as: "unfinalized"
    # end
  end
  get "utilisateurs/:id/instruments(/:target)" => "users#instruments"
  post "reunions/new" => "meetings#new"
  resources :meetings, :path => "reunions"

  namespace :api do

    get "main" => "api#main"

    get "/recherche/:term(/sur/:classes)" => "searches#index"

    resources :notifications, only: [:index, :destroy, :update] do
      collection do
        get "/page/:page" => "notifications#index"
      end
    end

    get "utilisateurs/courant" => "users#current", as: :current_user

    resources :medias, only: [:create, :destroy, :update]

    resources :users, only: [:create, :update, :show], path: 'utilisateurs' do
      member do
        put 'aime/:activity_id' => "users#toggle_like", :as => "toggle_like"
        post "push" => "users#push_subscribe"
        # FIXME : change post for delete method once we found a way to send endpoint (which is an URL) via the URL param
        post "push/unsubscribe" => "users#push_unsubscribe"
      end
    end

    devise_scope :user do
      post "sessions/se-connecter" => "sessions#create", as: "sessions"
    end

    resources :pages, only: [:index, :create, :show, :update], path: 'pages' do
      collection do
        get "/recherche/:search" => "pages#index"
      end
    end

    resources :instrument_preferences, path: "instruments"
    resources :activities, path: "activites" do
      collection do
        get "/sur/:recipient_type/:recipient_id(/page/:page)" => "activities#index"
        get "/page/:page" => "activities#index"
      end
      resources :comments, path: "commentaires", controller: 'activities/comments'
    end
    resources :posts, path: 'publications', only: [:show, :create, :update, :destroy]
  end

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'
end

app/models/user_song_preference.rb
class UserSongPreference < ApplicationRecord

  belongs_to :user
  belongs_to :song

end

app/controllers/user_song_preferences_controller.rb
class UserSongPreferencesController < ApplicationController
  before_action :set_user_song_preference, only: [:show, :edit, :update, :destroy]

  # GET /user_song_preferences
  # GET /user_song_preferences.json
  def index
    @user_song_preferences = UserSongPreference.all
  end

  # GET /user_song_preferences/1
  # GET /user_song_preferences/1.json
  def show
  end

  # GET /user_song_preferences/new
  def new
    @user_song_preference = UserSongPreference.new
  end

  # GET /user_song_preferences/1/edit
  def edit
  end

  # POST /user_song_preferences
  # POST /user_song_preferences.json
  def create
    @user_song_preference = UserSongPreference.new(user_song_preference_params)

    respond_to do |format|
      if @user_song_preference.save
        format.html { redirect_to @user_song_preference, notice: 'User song preference was successfully created.' }
        format.json { render :show, status: :created, location: @user_song_preference }
      else
        format.html { render :new }
        format.json { render json: @user_song_preference.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_song_preferences/1
  # PATCH/PUT /user_song_preferences/1.json
  def update

    respond_to do |format|
      if @user_song_preference.update(user_song_preference_params)
        format.html { redirect_to @user_song_preference, notice: 'User song preference was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_song_preference }
        format.js {}
      else
        format.html { render :edit }
        format.json { render json: @user_song_preference.errors, status: :unprocessable_entity }
        format.js {}
      end
    end
  end

  # DELETE /user_song_preferences/1
  # DELETE /user_song_preferences/1.json
  def destroy
    @user_song_preference.destroy
    respond_to do |format|
      format.html { redirect_to user_song_preferences_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_song_preference
      @user_song_preference = UserSongPreference.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_song_preference_params
      params.require(:user_song_preference).permit(:prefered_key, :prefered_capo)
    end
end

app/helpers/user_song_preferences_helper.rb
module UserSongPreferencesHelper
end

app/views/user_song_preferences/_form.html.erb
<%= simple_form_for(@user_song_preference) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/user_song_preferences/edit.html.erb
<h1>Editing user_song_preference</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_song_preference %> |
<%= link_to 'Back', user_song_preferences_path %>

app/views/user_song_preferences/index.html.erb
<h1>Listing user_song_preferences</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_song_preferences.each do |user_song_preference| %>
      <tr>
        <td><%= link_to 'Show', user_song_preference %></td>
        <td><%= link_to 'Edit', edit_user_song_preference_path(user_song_preference) %></td>
        <td><%= link_to 'Destroy', user_song_preference, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User song preference', new_user_song_preference_path %>

app/views/user_song_preferences/new.html.erb
<h1>New user_song_preference</h1>

<%= render 'form' %>

<%= link_to 'Back', user_song_preferences_path %>

app/views/user_song_preferences/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_user_song_preference_path(@user_song_preference) %> |
<%= link_to 'Back', user_song_preferences_path %>

app/views/user_song_preferences/update.js.erb
$('#song-container').html("<%= escape_javascript(render("songs/song_container", :song => @user_song_preference.song)) %>");
load_chords();